# -*- coding: utf-8 -*-
"""ML_lib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LXcohm6NHiEJ0FJocW-gXMXRslHEQ608
"""

import os
import numpy as np

import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

model_paths = {
    'basic': '/content/imdb_basic.keras'
}

class model_for_ranking:
  def __init__(self, type_model):
    self.model = tf.keras.models.load_model(model_paths[type_model])

  def rank(self, messages):
    tf_messages = tf.constant(messages)
    results = tf.sigmoid(self.model(tf_messages))
    return results.numpy().tolist()