name: CI/CD yml for backend airflow and postgres

on:
  push:
    branches:
      - main
      - feature/DevOps
  pull_request:
    branches:
      - main
      - feature/DevOps


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install docker-compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version


      - name: Prepare environment file
        run: |
          cp .env.example .env
          cat .env 

      # 2. Поднимаем инфраструктуру
      - name: Start containers
        run: |
          docker compose up -d --build tester

      - name: Run tests
        run: |
          docker-compose logs --follow tester > test.log && cat test.log